Question 1. 

Write a Python Program to Add Two Matrices?

Method 1

In [61]:
import numpy as np

def add_arr():
    r_arr1 = int(input("Enter the number of row in Matrix '1':  "))     ## Row inside the Matrice
    c_arr_1 = int(input("Enter the number of columns in Matrix 1:  "))  ## Column inside the Matrice
    
    elem_input_1 = list(map(int, input().split()))                      ## Each element required...if we are to use 2 x 2..then 4 inputs
    
    res_matrix_1 = np.array (elem_input_1). reshape((r_arr1, c_arr_1))  ## Numpy function to convert the inputs into arrays and shape them into Matrices
                                                                        ## 2 x 2 gives 2 rows and 2 columns.
        
    
    r_arr2 = int(input("Enter the number of row in Matrix '2':   "))    ## For the second Row
    c_arr_2 = int(input("Enter the number of columns in Matrix 2:  "))  ## Second Column
    
    elem_input_2 = list(map(int,input().split()))                       ## Inputs for the Second Matrice.
    
    res_matrix_2 = np.array (elem_input_2). reshape((r_arr2, c_arr_2))  ## Numpy function to create a Matrice with the inputs
    
    print ("Matrix 1 is: \n",  res_matrix_1)
    print ("Matrix 2 is: \n",  res_matrix_2)
    
    add_matrix = res_matrix_1 + res_matrix_2                           ## Create a variable that adds in both the Matrice and provide a New Matrice.
    
    return "Result of adding 2 matrix is", add_matrix

add_arr()

Enter the number of row in Matrix '1':  2
Enter the number of columns in Matrix 1:  2
1 2 3 4
Enter the number of row in Matrix '2':   2 
Enter the number of columns in Matrix 2:  2
5 6 7 8
Matrix 1 is: 
 [[1 2]
 [3 4]]
Matrix 2 is: 
 [[5 6]
 [7 8]]


('Result of adding 2 matrix is',
 array([[ 6,  8],
        [10, 12]]))

In [218]:
''' This is just working column



row_arr_1 = int(input("Enter the number of rows for matrix 1: "))
col_arr_1 = int(input("Enter the number of columns for matrix 1: ")) 
for i in range(row_arr_1):
    ele = []
    print(ele)
    for j in range(col_arr_1):
        ele.append(int(input()))
        print(ele)
        
''' 

Enter the number of rows for matrix 1: 2
Enter the number of columns for matrix 1: 2
[]
1
[1]
2
[1, 2]
[]
3
[3]
4
[3, 4]


Method 2

In [220]:
matrix_arr_1 = []
    
row_arr_1 = int(input("Enter the number of rows for matrix 1: "))       ## Input an integer for the Rows 
    
col_arr_1 = int(input("Enter the number of columns for matrix 1: "))   ## Input an integer for the Columns
    
for i in range (0, row_arr_1):                                        ##  For loop that goes Row First
    elem = []                                               ## Empty List which will be inside the For Loop for every time it iterates one space is created
    for j in range (0, col_arr_1):                          ## nested For Loop for every iteration an input inside will be included inside the 'elem' list
        elem.append(int(input()))                           ## Each time an empty array index is created from the first For Loop inside the elem = []
                                                            ## Then each iteration inside the nested For Loop allows the compiler to input an element inside the
                                                            ## elem = [] 
    matrix_arr_1.append(elem)                               ## All the elements inside the first empty list will be then appended inside the second list
        
print (matrix_arr_1)
                            

matrix_arr_2 = []
    
row_arr_2 = int(input("Enter the number of rows for matrix 2: "))
    
col_arr_2 = int(input("Enter the number of columns for matrix 2: "))
    
for i in range (0, row_arr_2):
    elem2 = []
        
    for j in range (0, col_arr_2):
        elem2.append(int(input()))
                
    matrix_arr_2.append(elem2)
print(matrix_arr_2)



new_arr_res = []                                   ## Create the same number/length of matrice which will have ame dimensions as the one abpve
for i in matrix_arr_1:                             ## This is an empty matrice which will have [0] value which will be temporary
    new_arr_res.append([0]*len(i))
print(new_arr_res)
                                       ## Inputs for 2 x 2 matrices are = Mat 1 --> [1,2] [3,4]    Mat 2 --> [5,6] [7,8]

for i in range(len(matrix_arr_1)):                 ## Again we use nested loop because when we choose '1,2' in first 2 elements it should be parallel to '5,6'
    for j in range(len(matrix_arr_2)):             ## Inside the second matrice '1' will be matched with '5' and '2' with '6' and so on
        new_arr_res[i][j] = matrix_arr_1[i][j] + matrix_arr_2[i][j]    ## Adding those elements with same indexes
print(new_arr_res)

Enter the number of rows for matrix 1: 2
Enter the number of columns for matrix 1: 2
1
2
3
4
[[1, 2], [3, 4]]
Enter the number of rows for matrix 2: 2
Enter the number of columns for matrix 2: 2
5
6
7
8
[[5, 6], [7, 8]]
[[0, 0], [0, 0]]
[[6, 8], [10, 12]]


Question 2.

Write a Python Program to Multiply Two Matrices?

In [226]:
## to create rows and columns we need one common input for the same

## First Matrice

def multiply_Matrices():

    arra_a = []

    dimensions = int(input("Enter a number for Matrix Dimension 1:  "))  

    for i in range(dimensions):
        row = []                                                             ## temporary list to store the rows
        for j in range(dimensions):
            row.append(int(input("Enter the elements inside the rows: ")))  ## enter the elements for the row

        arra_a.append(row)                                                 ## Store the elements from the row in the list

    print(arra_a)



    ## For Second Matrice

    arra_b = []

    dimensions = int(input("Enter a number for Matrix Dimension 2:  "))

    for i in range(dimensions):
        row = []                                                             ## temporary list to store the rows
        for j in range(dimensions):
            row.append(int(input("Enter the elements inside the rows: ")))  ## enter the elements for the row

        arra_b.append(row)                                                 ## Store the elements from the row in the list

    print(arra_b)





    result_arra = []
    for i in arra_a:
        result_arra.append([0]*len(i))
    print(result_arra)


    for i in range(len(arra_a)):
        for j in range(len(arra_b)):
            result_arra[i][j] = arra_a[i][j]*arra_b[i][j]

    print (result_arra)

In [227]:
multiply_Matrices()

Enter a number for Matrix Dimension 1:  2
Enter the elements inside the rows: 1
Enter the elements inside the rows: 2
Enter the elements inside the rows: 3
Enter the elements inside the rows: 4
[[1, 2], [3, 4]]
Enter a number for Matrix Dimension 2:  2
Enter the elements inside the rows: 5
Enter the elements inside the rows: 6
Enter the elements inside the rows: 7
Enter the elements inside the rows: 8
[[5, 6], [7, 8]]
[[0, 0], [0, 0]]
[[5, 12], [21, 32]]


Question 3. 

Write a Python Program to Transpose a Matrix?

In [224]:
def matrice_transpose():

    matrix_transpose = []

    tran_dimension = int(input("Enter an integer for Matrix Dimension:  "))

    for i in range(tran_dimension):
        row_transpose = []
        for j in range(tran_dimension):
            row_transpose.append(int(input("Enter the elements for the Matrix: ")))
        matrix_transpose.append(row_transpose)
    print(matrix_transpose)

    ## Create an empty matirx of the same dimensions

    res_transpose = []

    for i in matrix_transpose:
        res_transpose.append([0]*len(i))
    print(res_transpose)

                                                     ## The concept is the same for creating Matrices
    for i in range(len(matrix_transpose)):           ## In this one however we create 2 seperate variables for One Single Matrice
        for j in range(len(matrix_transpose)):
            res_transpose[j][i] = matrix_transpose[i][j]   ## This allows to switch places within the Matrices
    print(res_transpose)

In [225]:
matrice_transpose()

Enter an integer for Matrix Dimension:  2
Enter the elements for the Matrix: 1
Enter the elements for the Matrix: 2
Enter the elements for the Matrix: 3
Enter the elements for the Matrix: 4
[[1, 2], [3, 4]]
[[0, 0], [0, 0]]
[[1, 3], [2, 4]]


Question 4. 

Write a Python Program to Sort Words in Alphabetic Order?

In [222]:
def sort_words():

    complete_list = []
    while True:
        write_random = input("Enter words: ")

        if write_random == "stop":
            break
        complete_list.append(write_random)
    print(complete_list)

    for sort in sorted(complete_list):
        print (sort)

In [223]:
sort_words()

Enter words: apple
Enter words: havoc
Enter words: greenberry
Enter words: blackberry
Enter words: banana
Enter words: cherry
Enter words: guvava
Enter words: papaya
Enter words: stop
['apple', 'havoc', 'greenberry', 'blackberry', 'banana', 'cherry', 'guvava', 'papaya']
apple
banana
blackberry
cherry
greenberry
guvava
havoc
papaya


Question 5. 

Write a Python Program to Remove Punctuation From a String?

In [213]:
import re

text_with_char = input("Input random words with characters and expression: ")

opt = re.sub(r'[^\w\s]','', text_with_char)    ## re.sub allows replacement of a sub-string with another sub-string
                                               ## Inside the parenthesis the pattern was \w == word and \s == space....any other special characters
print(opt)                                     ## Will be replaced by '' which means it will be removed...works similar to split() or remove()

Input random words with characters and expression: row %^&**good
row good
