Question 1:

Write a program that calculates and prints the value according to the given formula:

Q = Square root of [(2 * C * D)/H]

Following are the fixed values of C and H:


C is 50. H is 30.

D is the variable whose values should be input to your program in a comma-separated
sequence.

Example
Let us assume the following comma separated input sequence is given to the program:

100,150,180

The output of the program should be:

18,22,24

In [23]:
import math  ## import math library to perform the in-built sqrt() function


def calculate_value():
    
    ## pre-defined variables
    
    C = 50  
    H = 30
    
    ## exception handling of entering 3 inputs and converting them into int objects
    
    try:
        entr_3_input = input(" Please enter 3 numbers seperated by a space: ")
        a, b, c = entr_3_input.split()             ## one input assigns 3 values for 3 variables
        
    except ValueError:
        print("Error")
        
    else:
        cnvrt_a = int(a)                          ## converting the values from string to int object
        cnvrt_b = int(b)
        cnvrt_c = int(c)
          
    res_1 = math.sqrt(2 * C * cnvrt_a // H)      ## Calculating the value with the given formula
    res_2 = math.sqrt(2 * C * cnvrt_b // H)
    res_3 = math.sqrt(2 * C * cnvrt_c // H)
    
    return round(res_1), round(res_2), round(res_3)

In [24]:
calculate_value()

 Please enter 3 numbers seperated by a space: 100 150 180


(18, 22, 24)

Question 2:


Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. 

The element value in the i-th row and j-th column of the array should be i*j.


Note: i=0,1.., X-1; j=0,1,¡Y-1.


Example:

Suppose the following inputs are given to the program:
3,5

Then, the output of the program should be:

[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

In [105]:
import numpy as np

def two_d_array(rows, columns):
    
    matrix = []         ## An empty list which will append the rows and columsn into a 2-D array
    for i in range(rows):
        row = []
        for j in range(columns):
            row.append(i * j)    
            
        matrix.append(row)
    arr = np.array(matrix)
    
        
# #     for i in range(rows):
# #         for j in range(columns):
# #             print(arr[i][j], end = " ")
#         print()

    print(arr)
    print(matrix)
    return
        
            

In [109]:
two_d_array(3, 5)

[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]


Question 3:

Write a program that accepts a comma separated sequence of words as input and prints the
words in a comma-separated sequence after sorting them alphabetically.

Suppose the following input is supplied to the program:

without,hello,bag,world

Then, the output should be:

bag,hello,without,world

In [354]:
def sorting_words():
    try:
        rand_words = input("Input random words seperated by a comma ")
        lst_words = [value for value in rand_words.split(",")]
        
    except:
        print("Please Enter only String Values")
        
    else:
        print(",".join(sorted(list(lst_words))))

        
    return


In [355]:
sorting_words()

Input random words seperated by a comma without,hello,bag,world,bag
bag,bag,hello,without,world


Question 4:

Write a program that accepts a sequence of whitespace separated words as input and prints

the words after removing all duplicate words and sorting them alphanumerically.

Suppose the following input is supplied to the program:

hello world and practice makes perfect and hello world again

Then, the output should be:

again and hello makes perfect practice world

In [360]:
def sort_space_duplicate():
    
    try:
        random_words_ = input("Random words seperated by a whitespace ").split()
        rmv_duplicates = list(dict.fromkeys(random_words_))
        
        lst_no_duplicates = list(set(random_words_))
        
    except:
        print("Invalid entry")
        
    else:
        print("Using built-in commnad fromkeys() --> "," ".join(sorted(rmv_duplicates)))
        print("Using set() command --> "," ".join(sorted(lst_no_duplicates)))
        
    return

In [361]:
sort_space_duplicate()

Random words seperated by a whitespace hello world and practice makes perfect and hello world again
Using built-in commnad fromkeys() again and hello makes perfect practice world
Using set() command again and hello makes perfect practice world


Question 5:

Write a program that accepts a sentence and calculate the number of letters and digits.

Suppose the following input is supplied to the program:

hello world! 123

Then, the output should be:

LETTERS 10

DIGITS  3

In [409]:
def check_alpha_num():
    
    alphabts_ = digits_ = charcters_  = ""
    
    entr_string_char = input("Enter Random alphanumeric values: ")
    
    for i in range(len(entr_string_char)):
#         if ((entr_string_char[i] >= "A" and entr_string_char[i] <= "Z") or (entr_string_char[i] >= "a" and entr_string_char[i] <= "z")):
#             alphabts_ = alphabts_ + entr_string_char[i]
            
    
        if (entr_string_char[i].isalpha()):
            alphabts_ = alphabts_ + entr_string_char[i]
        elif (entr_string_char[i].isdigit()):
            digits_ = digits_ + entr_string_char[i]
        else:
            charcters_ = charcters_ + entr_string_char[i]
            
    return "LETTERS: ", len(alphabts_), "DIGITS: ", len(digits_)
        
        

In [410]:
check_alpha_num()


Enter Random alphanumeric values: hello world !!@##@ 123


('LETTERS: ', 10, 'DIGITS: ', 3)

Question 6:

A website requires the users to input username and password to register. Write a program to
check the validity of password input by users.

Following are the criteria for checking the password:

1. At least 1 letter between [a-z]

2. At least 1 number between [0-9]

1. At least 1 letter between [A-Z]

3. At least 1 character from [$#@]

4. Minimum length of transaction password: 6

5. Maximum length of transaction password: 12

Your program should accept a sequence of comma separated passwords and will check them
according to the above criteria. Passwords that match the criteria are to be printed, each
separated by a comma.

Example

If the following passwords are given as input to the program:
ABd1234@1,  a F1#,  2w3E*,  2We3345

Then, the output of the program should be:
ABd1234@1

In [684]:
import string

def check_password():
    
# "PassWrd@$12"
    str_input = input()

    alpha_ = digit_ = lower_ = upper_ = char_ = ""



    if len(str_input) >= 6 and len(str_input) <= 12:
        for i in range(len(str_input)):

            if (str_input[i].isalpha()):
                alpha_ = alpha_ + str_input[i]

            if (str_input[i].isdigit()):
                digit_ = digit_ + str_input[i]

            if (str_input[i].islower()):
                lower_ = lower_ + str_input[i]

            if (str_input[i].isupper()):
                upper_ = upper_ + str_input[i]

            if (str_input[i] in string.punctuation):
                char_ = char_ + str_input[i]



    if len(alpha_) >= 1 and len(digit_) >= 1 and len(lower_) >= 1 and len(upper_) >= 1 and len(char_) >= 1 and len(alpha_ + digit_ + char_) >=6 and len (str_input) <= 12:
        print("Valid")

    else:
        print("Invalid")




In [685]:
check_password()

PASSWERD45@
Invalid
